pimcore:
    perspectives:
        definitions:
            PIM:
                elementTree:
                    -
                        type: customview
                        position: left
                        sort: 0
                        expanded: false
                        hidden: false
                        id: 37453cd8-4a48-5ff0-3430-4492beba96f7
                    -
                        type: customview
                        position: left
                        sort: 1
                        expanded: false
                        hidden: false
                        id: 975310ba-ee80-15d1-a831-d483129dd81c
                    -
                        type: customview
                        position: left
                        sort: 2
                        expanded: false
                        hidden: false
                        id: 6d1cceae-06fd-76f1-2458-da455daca6b5
                iconCls: null
                icon: null
                dashboards:
                    disabledPortlets:
                        pimcore.layout.portlets.modifiedObjects: 1
                toolbar:
                    file:
                        hidden: false
                        items:
                            perspectives: true
                            dashboards: true
                            openDocument: true
                            openAsset: true
                            openObject: true
                            searchReplace: true
                            schedule: true
                            seemode: true
                            closeAll: true
                            help: true
                            about: true
                    marketing:
                        hidden: false
                        items:
                            reports: true
                            tagmanagement: true
                            targeting: true
                            seo:
                                hidden: false
                                items:
                                    documents: true
                                    robots: true
                                    httperrors: true
                    extras:
                        hidden: false
                        items:
                            glossary: true
                            redirects: true
                            translations: true
                            recyclebin: true
                            plugins: true
                            notesEvents: true
                            applicationlog: true
                            gdpr_data_extractor: true
                            emails: true
                            maintenance: true
                            systemtools:
                                hidden: false
                                items:
                                    phpinfo: true
                                    opcache: true
                                    requirements: true
                                    database: true
                                    fileexplorer: true
                    settings:
                        hidden: false
                        items:
                            customReports: true
                            marketingReports: true
                            documentTypes: true
                            predefinedProperties: true
                            predefinedMetadata: true
                            system: true
                            appearance: true
                            website: true
                            web2print: true
                            users:
                                hidden: false
                                items:
                                    users: true
                                    roles: true
                            thumbnails: true
                            objects:
                                hidden: false
                                items:
                                    classes: true
                                    fieldcollections: true
                                    objectbricks: true
                                    quantityValue: true
                                    classificationstore: true
                                    bulkExport: true
                                    bulkImport: true
                            routes: true
                            cache:
                                hidden: false
                                items:
                                    clearAll: true
                                    clearData: true
                                    clearSymfony: true
                                    clearOutput: true
                                    clearTemp: true
                            adminTranslations: true
                            tagConfiguration: true
                            perspectiveEditor: true
                    search:
                        hidden: false
                        items:
                            quickSearch: true
                            documents: true
                            assets: true
                            objects: true
                    datahub:
                        hidden: false
