pimcore_data_hub:
    configurations:
        PlumbingCategoryExport:
            general:
                type: dataImporterDataObject
                name: PlumbingCategoryExport
                description: ''
                group: ''
                active: false
                path: null
                modificationDate: 1711256174
                createDate: 1711212427
            loaderConfig:
                type: upload
                settings:
                    uploadFilePath: PlumbingCategoryExport/upload.import
            interpreterConfig:
                type: xlsx
                settings:
                    skipFirstRow: true
                    sheetName: 'Category_Taxonomy Name & Code'
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: CategoryOrTaxonomy
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: '/Plumbing Taxonomy-Categories'
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangePublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'Category Name'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: CategoryName
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Category Code'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: CategoryCode
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Parent Category'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ParentCategory
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: '24-03-2024 00:00'
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
