pimcore_data_hub:
    configurations:
        testing:
            general:
                type: dataImporterDataObject
                path: null
                name: testing
                modificationDate: 1731733722
                createDate: 1731733722
            workspaces: {  }
            permissions:
                user: {  }
                role: {  }
